### PR TITLE
Ensure that dekorate dependencies don't end up in uber-jar

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Why don't you added this exclusion for the client then @geoand ?

**Comment by geoand** [comment]
I thought the client didn't contain dekorate, but I was wrong :)

**Comment by cmoulliard** [comment]
LGTM. Size of the client uber jar is now 20MB instead of 38Mb. Many thanks

**Comment by geoand** [comment]
You are welcome!

**Comment by geoand** [comment]
Just to be on the safe side:

@iocanel removing the dekorate jars from the spring boot uber jar should not create any problems, correct?

**Comment by geoand** [comment]
@cmoulliard the `k8s-dev-e2e-test` job seems to be failing, is that expected?

**Comment by geoand** [comment]
I should mention that it fails with a `microk8s` error: `- Download snap "microk8s" (581) from channel "1.13/stable" (stream error: stream ID 1; PROTOCOL_ERROR)`

**Comment by metacosm** [comment]
So Spring Boot also include compile dependencies?

**Comment by geoand** [comment]
`compile` is the maven default, no? And maven doesn't have any `compile-only` unfortunately...

**Pull request merged**
