### PR TITLE
feat: use halkyon.io/api for the API instead of embedding it

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by cmoulliard** [comment]
LGTM. We could merge it @metacosm

**Comment by cmoulliard** [comment]
Is this PR ready to be merged @metacosm ?

**Comment by metacosm** [comment]
> Is this PR ready to be merged @metacosm ?

Tests need to pass first…

**Comment by metacosm** [comment]
Also, merging this branch will mean that master will only work with dekorate snapshot as well. So we'd need a new dekorate release first actually.

**Comment by cmoulliard** [comment]
Can you remove from the the 2 `application.yml` files of demo ```server: port: 8080``` as this is not needed because this is generated by dekorate ? @metacosm

**Comment by cmoulliard** [comment]
What do we do ? Wait till dekorate 0.8.1 is released to test it ? @metacosm

**Comment by metacosm** [comment]
@cmoulliard yes, plus it looks like the branch needs to be updated

**Pull request merged**
