### PR TITLE
chore: move to proper org and project name

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by metacosm** [comment]
Todo:

- [ ] update documentation
- [ ] update quay.io information
- [ ] update CircleCI configuration
- [ ] update demo

**Comment by cmoulliard** [comment]
quay.io org created -> `https://quay.io/organization/halkyonio`

**Comment by cmoulliard** [comment]
Can we merge it @metacosm ?

**Comment by cmoulliard** [comment]
LGTM.

**Pull request merged**
